version: '3.4'

services:
  backend:
    image: graham-uno-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    networks:
       graham-network:
        ipv4_address: 10.5.0.2
    depends_on:
        db:
          condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: graham-uno-dev
      POSTGRES_USER: graham
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      graham-network:
        ipv4_address: 10.5.0.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graham-uno-dev"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

networks:
  graham-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
