
name: Test BackEnd

on:
  workflow_dispatch:
  #esto es para poder ejecutar el workflow sin necesidad de hacer un commit a main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio al ejecutor
        uses: actions/checkout@v4

      - name: Compilar aplicacion
        run: npm run build
