name: Cypress Tests

on:
    workflow_dispatch:
    #esto es para poder ejecutar el workflow sin necesidad de hacer un commit a main
  
    push:
      branches:
        - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci
    
      - name: Instalar Cypress
        run: npm install cypress --save-dev

      - name: Actualizar dependencias
        run: npm update

      - name: Actualizar ESLint a la última versión disponible 
        run: npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev

      - name: Compilar proyecto
        run: npm run build

      - name: Lint
        run: npm run eslint

      - name: Lanzar app
        run: npm run start-test

      - name: Test E2E
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:e2e
            # start: npm run start-test
            wait-on: http://localhost:8000
