name: Cypress Tests

on:
    workflow_dispatch:
    #esto es para poder ejecutar el workflow sin necesidad de hacer un commit a main
  
    push:
      branches:
        - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      - name: Instalar dependencias
        run: npm install --no-audit --no-fund --no-optional
    
      - name: Actualizar dependencias
        run: npm update

      - name: Actualizar ESLint a la última versión disponible 
        run: npm install eslint@latest --save-dev

      - name: Lint
        run: npm run lint

      - name: Compilar proyecto
        run: npm run build

      - name: Preparar los tests de cypress de tests.js
        run: npm run start-test

      - name: Run Cypress tests
        run: npx cypress run
